import { defineConfig } from "astro/config";
import react from "@astrojs/react";
import mdx from "@astrojs/mdx";
import tailwindcss from "@tailwindcss/vite";

/**
 * Sitemaps are generated by src/pages/sitemap-[locale].xml.ts and
 * src/pages/sitemap-index.xml.ts rather than @astrojs/sitemap, so that each
 * language gets its own file and the priority rules can read the pages'
 * actual identity instead of pattern-matching localized slugs.
 */
export default defineConfig({
  site: "https://storagecalculators.com",
  trailingSlash: "ignore",
  integrations: [react(), mdx()],
  vite: {
    plugins: [tailwindcss()],
  },
  build: {
    format: "directory",
  },
});
