import { rename, rm } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { defineConfig } from "astro/config";

/**
 * Emits Cloudflare's `_redirects` from src/pages/redirects-cf.txt.ts.
 * Astro refuses to route a file whose name starts with "_", so the rules are
 * generated under a temporary name and moved into place after the build.
 */
function cloudflareRedirects() {
  return {
    name: "cloudflare-redirects",
    hooks: {
      "astro:build:done": async ({ dir, logger }) => {
        const root = fileURLToPath(dir);
        const from = `${root}redirects-cf.txt`;
        const to = `${root}_redirects`;
        await rename(from, to);
        await rm(`${root}redirects-cf.txt`, { force: true });
        logger.info("wrote _redirects");
      },
    },
  };
}
import react from "@astrojs/react";
import mdx from "@astrojs/mdx";
import tailwindcss from "@tailwindcss/vite";

/**
 * Sitemaps are generated by src/pages/sitemap-[locale].xml.ts and
 * src/pages/sitemap-index.xml.ts rather than @astrojs/sitemap, so that each
 * language gets its own file and the priority rules can read the pages'
 * actual identity instead of pattern-matching localized slugs.
 */
export default defineConfig({
  site: "https://storagecalculators.com",
  trailingSlash: "ignore",
  integrations: [react(), mdx(), cloudflareRedirects()],
  vite: {
    plugins: [tailwindcss()],
  },
  build: {
    format: "directory",
  },
});
